[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "a81bd38b8d5212f36c6b7fbe09562daef575cf20"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenSpecFun.download]]
    sha256 = "ab554a6e09e550788d0a9540ab6e5782edc0bd0f6a5d4bbcbe26b84ed4d625f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "c17af22e6abd5b4566ded8fe3d9e50e169024823"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenSpecFun.download]]
    sha256 = "3cac3c566b83794e51095fe31ed1c332add004e4ea2020ec23f35a6e136d3098"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "a0a2aa24d3274c468a81e7608e027462a3f99f53"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenSpecFun.download]]
    sha256 = "f8cbf6b715714a78f4c0918cb13d3dcd9b3b4dd6fe95c93368d7235737d53ef2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "aarch64"
git-tree-sha1 = "afcf16fd8dc3dd37a1064e58382a27867d9e02ba"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "38d3f7cd4605f66c2a267c516e7e3529652de52a9c2c9ecad6f9bd2c312d8ea7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "3dbfd5bf6045a48454ec4965785f56a74b68cb93"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenSpecFun.download]]
    sha256 = "7ed1ab7fbb90ea6bc947363ab039a48055d5a4633d34cc21ab673fbdfbdac4bd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "efe2ffd78244699b9b1136a832403b93ab347db0"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenSpecFun.download]]
    sha256 = "3ce91ef1c169fbc3eff30b3f7c410c0a384067942c16cc97cd86d649029551ba"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "armv7l"
git-tree-sha1 = "dfe96003abe75ce4f6d3bd89a716ad7038e221a4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "44fec983f44aa2ded8874dcef5bd3d4d98515e8f02c3c33d1f02badc79fba6d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "41ec9bc0fd4a0e43e7375cba2817a52e8a4ceba6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "3444a014a5ef96df60330b41ea0518c7a6d7f5a25adb3344a5bbdf5dfebc9a9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "f96819049555f0d17b9bcb9821e367ec36d8c9a5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "b890992f98176b6eaa0e20c161f311fb928f1c64a3112d83ab5172955377f652"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-linux-musl-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "powerpc64le"
git-tree-sha1 = "b963f366a7f53aefbcfe59233b3d79a28be43116"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "f676a0afd76f3a9949849ff154feb28bd8e7f803b78d136bc04b668ef75ba114"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "armv7l"
git-tree-sha1 = "59e4e829ca404d39a2fe19787ac2427e61176f89"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "aa8be50271dd47db9f70991901c10893327361e728fa701ad8083fed4a99590c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "aarch64"
git-tree-sha1 = "78884f1a45d81c2733e5ce465a6c56dbbe776226"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "5c859adebff96f558188ce4a00de332996eb080b5d8e3bf017d43e2d5f4c3492"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "powerpc64le"
git-tree-sha1 = "96169652ae5d1f5b637207e0259e5ff231c81b7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "ae7d66c6d8ef4eca5df10839e96d736fc27124728eb2f0cf84e55deb87dfd6dd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "b9033dc7361784706d5421680c14a02aa4352319"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenSpecFun.download]]
    sha256 = "0c50906f0bfc410b02b736cae94c8ea7b92ae0596ea98e6cf02a3ccd4df0993b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "armv7l"
git-tree-sha1 = "8eef8b6f976caf6bca45174ef1c00f0054beffed"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "3aa14126323c227c050b589230f21f3b2d445c6e798d255d3d430be51f90b7d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "aarch64"
git-tree-sha1 = "f84e8ebce0b0775c25abcc0e346551a24e5566ac"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "e0abd1288b9fe623630f05665d2f9ad6c8e060aded057a4ddb98a0cd93d851bf"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "ecae3a3d7c5ccdbf685da1bf4e2214b86850fecc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "103fef6ff3c522a632e5035650e3da32cdb9b4b6543abaa741fc57f3e1cd6c3f"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "armv7l"
git-tree-sha1 = "5e57ec4c22568f24f32d0e3dcc1a6db353a425b2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "16563936e9d7e3b4d26daafa0223fbf0ec0bd66ce00526d43a85714f0778f19e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "bfc0351ae64a9928cba8b766dbdf004bcee73b71"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenSpecFun.download]]
    sha256 = "5ff2320d7a3f0a43374652a806060700c32f6eddd5d0e752c1fa4c849ab205bf"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "9aa38844b578390317585b31f707b9eb2d01cdaa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "aacc9c008863f1ccf4ff9bbe9be16450381ac96c329b67ded8f96f46fdb18ba1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "2a24f31bd9110ef151a0e064047ecf4baab999a9"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenSpecFun.download]]
    sha256 = "77f64b82c121f1ca0e342a1ce42b4e86788fd667106180a8caa64169bf059bc4"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "18d8540b8658a2390206aed03430bf5b9b9fcdb0"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenSpecFun.download]]
    sha256 = "79a4be04fc412a2b2c4119a3a307799885728fcb91dddbee13788e636583dab6"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "cc982ab677a9610a13118bbcab6122706934d883"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenSpecFun.download]]
    sha256 = "08ff6a5af7d6d46aace8d9907280c04a9caaffa66ed7b4388ff089b0e0621e40"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "aarch64"
git-tree-sha1 = "4b8de7979a6331417d349092a400a461f2a2fd6a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "a1777fc5558c11fead87791c3eca10da4550a35d9475062ecc5e857a5f10b352"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "31fc9303a38a7b157166f524c4e5c1607bd5c232"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "3541536804f92b6cd77de0839c2289d8b37bfb1b95e165f6d67e95c3e295b426"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "8aaab519901dc3a6a5f18d24c71faf8a4bfb2991"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "0b18ca8892a363758eb165d2c4eeb40d90f31e2129bb4c389888da049da7519a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "534a2270f6e6835c9105a72840155444c58110c3"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenSpecFun.download]]
    sha256 = "c71857ba0033ebbe73076461c486e54664b22260630c9b8548d5ecea072b86cd"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "armv7l"
git-tree-sha1 = "1fa6111b7c2181b4a9318e8e0bd209630699cac3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "a75ba7ae56d93770177fd50da0f6a43ece344edb52133955e8550eedc9799b2c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "79ed7c1a2f91e7f0876da60f9ea769c28b345a53"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "9b6637b937d67f8aa97e8013ad3a80b3d5156ea9d124d81849e7fa5869288781"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "6d870ac4c585d1115c7cb741b6d5ffddb2937505"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "32368a973ffdb6f0db31bda317a01d55e56f3cbd7e728f9601bf419a4b3c875a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "aarch64"
git-tree-sha1 = "ac16e356cad94a327e0c4e9a8104fa74293cf2f0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "7cc9fb56b9b235f301ccb19ddf8208dfea9a138e42b6aab35cbaaa778d6e84e1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "91c83c9b8486f32a2d1f59d447b83733d591c7c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "29c0c42909077257c48260c948500f5993bd8a444e7faedb3bdc696a07ef69d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "d07e607a121dc3ba6b98941565403a8a43d2b44f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "8974e0e46206d4a9c132c8754f23938dfc2f28ecdfefc459eca51b2fb91e9781"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "x86_64"
git-tree-sha1 = "d070492fd1804a1acb22e09aa6f4eacbf64085f1"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenSpecFun.download]]
    sha256 = "b283ec5bf619fdff03e81ee795fa6abda48419916b188f2b955299c675fbef58"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "5f5db2666160b238d8f2d54b09bf42bf643e198e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "02d91f7ef4a5c23aa18fba4cd4755b5d0eed0b261a7c6ffc23f0c4fac57f0f5e"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-linux-musl-libgfortran3.tar.gz"
[[OpenSpecFun]]
arch = "armv7l"
git-tree-sha1 = "187869632b381582da1aeff16f54b89e8d717363"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "98a6e06ed3e589948bfe4f279ce4305dd2bdba5610f7b3eda1945a9027bb7633"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "i686"
git-tree-sha1 = "2769fa303de354322680a91600adbf1d1ea46ba8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "8c8ad65f232fe29498ed123a4fbcacaf5700aeaa2d6117d7b89ce14447274df1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.i686-linux-musl-libgfortran4.tar.gz"
[[OpenSpecFun]]
arch = "aarch64"
git-tree-sha1 = "f483b13cc7a813fb1baa036d4fb960175e5181d9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "7efbdccd65c40b0887026eadc244537f83b6be5a3359bd04badfb2f23dbab309"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenSpecFun]]
arch = "powerpc64le"
git-tree-sha1 = "f1946a0648b13f0903ab60e3b114d771ffc7f268"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenSpecFun.download]]
    sha256 = "7ca30a32064868ea4e8b2323972799822b1fa7fb5ff29db1e3b067ea05fa0340"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+2/OpenSpecFun.v0.5.3.powerpc64le-linux-gnu-libgfortran4.tar.gz"
